version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shortenurl
    ports:
      - '3080:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

